leads = [
    {
        "id": 1,
        "nome do lead": "João Silva",
        "email": "joao.silva@example.com",
        "telefone": "45999990000",
        "origem": "Facebook",
        "status": "NOVO",
        "responsavel": "felipe@prati.com",
        "empreendimento": "Carmel",
        "motivo da escolha do empreendimento": "Gostou da localização",
        "midia de visita": "Instagram",
        "ponto de venda": "Online",
        "conversão": "Sim",
        "tags": ["interessado", "alto potencial"],
        "email alternativo": "joao.silva.alt@example.com",
        "telefone alternativo": "45999991111",
        "sexo": "Masculino",
        "renda familiar": "5000-10000",
        "cep": "12345-678",
        "pessoa estrangeira": "Não",
        "informar CPF": "Sim",
        "informar CNPJ": "Sim",
        "endereço": "Rua das Flores, 123",
        "numero": "123",
        "bairro": "Centro",
        "profissão": "Engenheiro",
    },
     {
        "id": 2,
        "nome do lead": "João Silva",
        "email": "joao.silva@example.com",
        "telefone": "45999990000",
        "origem": "Facebook",
        "status": "NOVO",
        "responsavel": "felipe@prati.com",
        "empreendimento": "Carmel",
        "motivo da escolha do empreendimento": "Gostou da localização",
        "midia de visita": "Instagram",
        "ponto de venda": "Online",
        "conversão": "Sim",
        "tags": ["interessado", "alto potencial"],
        "email alternativo": "joao.silva.alt@example.com",
        "telefone alternativo": "45999991111",
        "sexo": "Masculino",
        "renda familiar": "5000-10000",
        "cep": "12345-678",
        "pessoa estrangeira": "Não",
        "informar CPF": "Sim",
        "informar CNPJ": "Sim",
        "endereço": "Rua das Flores, 123",
        "numero": "123",
        "bairro": "Centro",
        "profissão": "Engenheiro",
    },

    {
    "id": 3,
    "nome do lead": "Maria Oliveira",
    "email": "maria.oliveira@example.com",
    "telefone": "45988881234",
    "origem": "Google Ads",
    "status": "EM CONTATO",
    "responsavel": "ana@prati.com",
    "empreendimento": "Aurora",
    "motivo da escolha do empreendimento": "Preço acessível",
    "midia de visita": "Facebook",
    "ponto de venda": "Plantão",
    "conversão": "Não",
    "tags": ["interessado"],
    "email alternativo": "maria.alt@example.com",
    "telefone alternativo": "45988884567",
    "sexo": "Feminino",
    "renda familiar": "2000-5000",
    "cep": "85800-000",
    "pessoa estrangeira": "Não",
    "informar CPF": "Sim",
    "informar CNPJ": "Não",
    "endereço": "Av. Brasil, 450",
    "numero": "450",
    "bairro": "Jardim América",
    "profissão": "Professora"
},
{
    "id": 4,
    "nome do lead": "Carlos Pereira",
    "email": "carlos.pereira@example.com",
    "telefone": "45977771234",
    "origem": "Indicação",
    "status": "QUALIFICADO",
    "responsavel": "felipe@prati.com",
    "empreendimento": "Carmel",
    "motivo da escolha do empreendimento": "Segurança do condomínio",
    "midia de visita": "Instagram",
    "ponto de venda": "Online",
    "conversão": "Sim",
    "tags": ["alto potencial", "pronto para compra"],
    "email alternativo": "carlos.alt@example.com",
    "telefone alternativo": "45977774567",
    "sexo": "Masculino",
    "renda familiar": "10000-15000",
    "cep": "85900-000",
    "pessoa estrangeira": "Não",
    "informar CPF": "Sim",
    "informar CNPJ": "Não",
    "endereço": "Rua Paraná, 88",
    "numero": "88",
    "bairro": "Centro",
    "profissão": "Advogado"
},
{
    "id": 5,
    "nome do lead": "Ana Souza",
    "email": "ana.souza@example.com",
    "telefone": "45966661234",
    "origem": "Instagram",
    "status": "NOVO",
    "responsavel": "ana@prati.com",
    "empreendimento": "Aurora",
    "motivo da escolha do empreendimento": "Design moderno",
    "midia de visita": "Instagram",
    "ponto de venda": "Online",
    "conversão": "Não",
    "tags": ["curioso"],
    "email alternativo": "ana.alt@example.com",
    "telefone alternativo": "45966664567",
    "sexo": "Feminino",
    "renda familiar": "3000-7000",
    "cep": "85700-000",
    "pessoa estrangeira": "Não",
    "informar CPF": "Não",
    "informar CNPJ": "Não",
    "endereço": "Rua das Palmeiras, 210",
    "numero": "210",
    "bairro": "Vila Nova",
    "profissão": "Designer"
},
{
    "id": 6,
    "nome do lead": "Lucas Almeida",
    "email": "lucas.almeida@example.com",
    "telefone": "45955551234",
    "origem": "Facebook",
    "status": "PERDIDO",
    "responsavel": "felipe@prati.com",
    "empreendimento": "Carmel",
    "motivo da escolha do empreendimento": "Mudou de cidade",
    "midia de visita": "Google",
    "ponto de venda": "Online",
    "conversão": "Não",
    "tags": ["sem retorno"],
    "email alternativo": "lucas.alt@example.com",
    "telefone alternativo": "45955554567",
    "sexo": "Masculino",
    "renda familiar": "7000-12000",
    "cep": "85600-000",
    "pessoa estrangeira": "Não",
    "informar CPF": "Sim",
    "informar CNPJ": "Não",
    "endereço": "Rua São João, 32",
    "numero": "32",
    "bairro": "Industrial",
    "profissão": "Analista de Sistemas"
}


]